global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "alert_rules.yml"

scrape_configs:
  # Prometheus próprio
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Sua API FrotaMais
  - job_name: 'api-frotamais'
    static_configs:
      - targets: ['api-frotamais:4040']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Métricas do sistema
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Métricas dos containers
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Métricas do PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Métricas do RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']